# pylint: disable=unused-wildcard-import
from sonnenbatterie import const
from sonnenbatterie.const import SONNEN_OPEATING_MODES, SONNEN_OPERATING_MODE_MANUAL_NAME, SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME, SONNEN_OPERATING_MODE_BATTERY_MODULE_EXTENSION_30_PERCENT_NAME,SONNEN_OPERATING_MODE_TIME_OF_USE_NAME
from .const import SONNEN_MODEL_HYBRID_953_9010_ND_NAME, SONNEN_MODEL_UNKNOWN_NAME
# pylint: enable=unused-wildcard-import

# This is all the operating modes, basically it's the default if we don't find a matching battery
SONNEN_BATTERY_ALL_OPERATING_MODES=SONNEN_OPEATING_MODES

# list of the battery names we know of, the name is reported from the battery_system.system.model_name
SONNEN_MODEL_HYBRID_953_9010_ND_NAME='hyb 9.53 9010 ND'
SONNEN_MODEL_UNKNOWN_NAME="UNKNOWN"

SONNEN_OPERATING_MODE_AUTOMATIC_NICKNAME_LONG="Automatic"
SONNEN_OPERATING_MODE_AUTOMATIC_NICKNAME_SHORT="Auto"
SONNEN_OPERATING_MODE_AUTOMATIC_NICKNAME_CHAR="A"
SONNEN_OPERATING_MODE_MANUAL_NICKNAME_LONG="Manual"
SONNEN_OPERATING_MODE_MANUAL_NICKNAME_SHORT="Man"
SONNEN_OPERATING_MODE_MANUAL_NICKNAME_CHAR="M"
SONNEN_OPERATING_MODE_TOU_NICKNAME_LONG="Time Of Use Schedule"
SONNEN_OPERATING_MODE_TOU_NICKNAME_SHORT="TOU"
SONNEN_OPERATING_MODE_TOU_NICKNAME_CHAR="T"


# This is the mapping of the modes by each battery
# currently the 953 hybrid is the only sonnen I have access to, and thus the only one who'se modes I am aware of
SONNEN_MODEL_HYBRID_953_9010_ND_OPERATING_MODES=[SONNEN_OPERATING_MODE_MANUAL_NAME, SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME, SONNEN_OPERATING_MODE_BATTERY_MODULE_EXTENSION_30_PERCENT_NAME,SONNEN_OPERATING_MODE_TIME_OF_USE_NAME ]

# this map allows us to locate the msupported modes by the provided battery type
SONNEN_BATTERY_TO_OPERATING_MODES={SONNEN_MODEL_HYBRID_953_9010_ND_NAME:SONNEN_MODEL_HYBRID_953_9010_ND_OPERATING_MODES, SONNEN_MODEL_UNKNOWN_NAME:SONNEN_BATTERY_ALL_OPERATING_MODES}

# list of mode names we use

# this is a map of mappings for a nickname into the actual operating mode name, there are mappings for each battery type to allow diffeent mappings to happen for each battery
SONNEN_MODE_NICKNAME_TO_MODE_NAME_DEFAULT={SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME:SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME, 
                                           SONNEN_OPERATING_MODE_AUTOMATIC_NICKNAME_LONG:SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME, 
                                           SONNEN_OPERATING_MODE_AUTOMATIC_NICKNAME_SHORT:SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME, 
                                           SONNEN_OPERATING_MODE_AUTOMATIC_NICKNAME_CHAR:SONNEN_OPERATING_MODE_AUTOMATIC_SELF_CONSUMPTION_NAME, 
                                           SONNEN_OPERATING_MODE_BATTERY_MODULE_EXTENSION_30_PERCENT_NAME:SONNEN_OPERATING_MODE_BATTERY_MODULE_EXTENSION_30_PERCENT_NAME, 
                                           SONNEN_OPERATING_MODE_MANUAL_NAME:SONNEN_OPERATING_MODE_MANUAL_NAME, 
                                           SONNEN_OPERATING_MODE_MANUAL_NICKNAME_LONG:SONNEN_OPERATING_MODE_MANUAL_NAME, 
                                           SONNEN_OPERATING_MODE_MANUAL_NICKNAME_SHORT:SONNEN_OPERATING_MODE_MANUAL_NAME, 
                                           SONNEN_OPERATING_MODE_MANUAL_NICKNAME_CHAR:SONNEN_OPERATING_MODE_MANUAL_NAME,
                                           SONNEN_OPERATING_MODE_TIME_OF_USE_NAME:SONNEN_OPERATING_MODE_TIME_OF_USE_NAME,
                                           SONNEN_OPERATING_MODE_TOU_NICKNAME_LONG:SONNEN_OPERATING_MODE_TIME_OF_USE_NAME,
                                           SONNEN_OPERATING_MODE_TOU_NICKNAME_SHORT:SONNEN_OPERATING_MODE_TIME_OF_USE_NAME,
                                           SONNEN_OPERATING_MODE_TOU_NICKNAME_CHAR:SONNEN_OPERATING_MODE_TIME_OF_USE_NAME}

SONNEN_BATTERY_NAMES_MAPPINGS={SONNEN_MODEL_HYBRID_953_9010_ND_NAME:SONNEN_MODE_NICKNAME_TO_MODE_NAME_DEFAULT,
                               SONNEN_MODEL_UNKNOWN_NAME:SONNEN_MODE_NICKNAME_TO_MODE_NAME_DEFAULT}